#!/bin/bash

# Load config
set -o allexport
source "$VAULTWARDEN_CONFIG"
set +o allexport

# Create data dir
cd /var/lib/vaultwarden
mkdir -p "${DATA_FOLDER:-data}"

# Use default web vault folder
export WEB_VAULT_FOLDER="${WEB_VAULT_FOLDER:-"/usr/share/vaultwarden-web-vault/htdocs"}"

# Exec vaultwarden
exec /usr/bin/vaultwarden
