#!/bin/bash

# Load config
set -o allexport
source "$BITWARDEN_RS_CONFIG"
set +o allexport

# Create data dir
cd /var/lib/bitwarden_rs
mkdir -p "${DATA_FOLDER:-data}"

# Use default web vault folder
export WEB_VAULT_FOLDER="${WEB_VAULT_FOLDER:-"/usr/share/bitwarden_rs-web-vault/htdocs"}"

# Exec bitwarden
exec /usr/bin/bitwarden_rs
